# Generated by Django 4.0.4 on 2022-05-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date',
            field=models.DateField(verbose_name='bookmark date'),
        ),
    ]
