# Generated by Django 4.0.4 on 2022-05-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reader_alter_bookmark_options_alter_bookmark_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(to='main_app.reader'),
        ),
        migrations.AddField(
            model_name='reader',
            name='name',
            field=models.CharField(default='jhjf', max_length=50),
            preserve_default=False,
        ),
    ]
